on: pull_request
name: Linting
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: NPM Install
      uses: actions/npm@master
      with:
        args: install
    - name: Lint
      uses: actions/npm@master
      with:
        args: "run flow"