on:
  push:
    branches:
    - main

name: Build, Test, and Publish
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        npm publish --access public
